version: '3'
services:
  graphdb:
    image: ontotext/graphdb:10.1.5-arm64
    ports:
      - 7200:7200
      - 7300:7300
    entrypoint: [ "/opt/graphdb/entrypoint.sh" ]
    volumes:
      - ./.graphdb-data:/opt/graphdb/home    
      - ./RDF:/opt/graphdb/home/graphdb-import
      - old:/opt/graphdb/home/graphdb-import/old
      - ./graphdb-repo-config.ttl:/opt/graphdb/graphdb-repo-config.ttl
      - ./entrypoint.sh:/opt/graphdb/entrypoint.sh
    environment:  
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dinfer.pool.size=4
  nginx:
    image: arm64v8/nginx:latest
    depends_on:
      - graphdb
      - nextjs
    ports:
      - 8080:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  nextjs:
    build:
      context: ui
      args:
        NEXT_PUBLIC_SPARQL_ENDPOINT: http://localhost:8080/sparql
volumes:
  old: